package reservation

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// ReservationListItem is the data shape returned by the API.
// Product and Tenant information comes from JOINs for display purposes.
type ReservationListItem struct {
	ReservationID int64  `json:"reservation_id"`
	ProductID     int64  `json:"product_id"`
	TenantID      int64  `json:"tenant_id"`
	TenantName    string `json:"tenant_name"`
	SKU           string `json:"sku"`
	ProductName   string `json:"product_name"`
	ReservedQty   int    `json:"reserved_qty"`
	Status        string `json:"status"`
}

// CreateReservationInput represents the JSON payload
// required to create a Reservation.
type CreateReservationInput struct {
	ProductID   int64  `json:"product_id"`
	ReservedQty int    `json:"reserved_qty"`
	Status      string `json:"status"`
}

// UpdateReservationInput represents the complete editable state
// supplied when updating an existing Reservation.
type UpdateReservationInput struct {
	ProductID   int64  `json:"product_id"`
	ReservedQty int    `json:"reserved_qty"`
	Status      string `json:"status"`
}

// List returns all Reservations together with related Product
// and Tenant information.
func List(
	ctx context.Context,
	db *pgxpool.Pool,
) ([]ReservationListItem, error) {
	rows, err := db.Query(ctx, `
		SELECT
			r.reservation_id,
			r.product_id,
			p.tenant_id,
			t.tenant_name,
			p.sku,
			p.product_name,
			r.reserved_qty,
			r.status
		FROM reservations r
		JOIN products p
			ON r.product_id = p.product_id
		JOIN tenants t
			ON p.tenant_id = t.tenant_id
		ORDER BY r.reservation_id;
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	// Empty slice becomes [] in JSON instead of null.
	reservations := make([]ReservationListItem, 0)

	for rows.Next() {
		var r ReservationListItem

		if err := rows.Scan(
			&r.ReservationID,
			&r.ProductID,
			&r.TenantID,
			&r.TenantName,
			&r.SKU,
			&r.ProductName,
			&r.ReservedQty,
			&r.Status,
		); err != nil {
			return nil, err
		}

		reservations = append(reservations, r)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return reservations, nil
}

// GetByID returns one Reservation by its primary key.
func GetByID(
	ctx context.Context,
	db *pgxpool.Pool,
	reservationID int64,
) (ReservationListItem, error) {
	var r ReservationListItem

	err := db.QueryRow(ctx, `
		SELECT
			r.reservation_id,
			r.product_id,
			p.tenant_id,
			t.tenant_name,
			p.sku,
			p.product_name,
			r.reserved_qty,
			r.status
		FROM reservations r
		JOIN products p
			ON r.product_id = p.product_id
		JOIN tenants t
			ON p.tenant_id = t.tenant_id
		WHERE r.reservation_id = $1;
	`, reservationID).Scan(
		&r.ReservationID,
		&r.ProductID,
		&r.TenantID,
		&r.TenantName,
		&r.SKU,
		&r.ProductName,
		&r.ReservedQty,
		&r.Status,
	)

	if err != nil {
		return ReservationListItem{}, err
	}

	return r, nil
}

// Create inserts a new Reservation and returns
// the reservation_id generated by PostgreSQL.
func Create(
	ctx context.Context,
	db *pgxpool.Pool,
	input CreateReservationInput,
) (int64, error) {
	var reservationID int64

	err := db.QueryRow(ctx, `
		INSERT INTO reservations (
			product_id,
			reserved_qty,
			status
		)
		VALUES ($1, $2, $3)
		RETURNING reservation_id;
	`,
		input.ProductID,
		input.ReservedQty,
		input.Status,
	).Scan(&reservationID)

	if err != nil {
		return 0, err
	}

	return reservationID, nil
}

// Update modifies an existing Reservation.
//
// RowsAffected is checked because UPDATE can execute successfully
// while matching zero rows.
func Update(
	ctx context.Context,
	db *pgxpool.Pool,
	reservationID int64,
	input UpdateReservationInput,
) error {
	commandTag, err := db.Exec(ctx, `
		UPDATE reservations
		SET
			product_id = $1,
			reserved_qty = $2,
			status = $3
		WHERE reservation_id = $4;
	`,
		input.ProductID,
		input.ReservedQty,
		input.Status,
		reservationID,
	)
	if err != nil {
		return err
	}

	if commandTag.RowsAffected() == 0 {
		return pgx.ErrNoRows
	}

	return nil
}

// Delete removes one Reservation by its primary key.
func Delete(
	ctx context.Context,
	db *pgxpool.Pool,
	reservationID int64,
) error {
	commandTag, err := db.Exec(ctx, `
		DELETE FROM reservations
		WHERE reservation_id = $1;
	`, reservationID)
	if err != nil {
		return err
	}

	if commandTag.RowsAffected() == 0 {
		return pgx.ErrNoRows
	}

	return nil
}
