package product

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type ProductListItem struct {
	ProductID   int64   `json:"product_id"`
	TenantID    int64   `json:"tenant_id"`
	TenantName  string  `json:"tenant_name"`
	SKU         string  `json:"sku"`
	ProductName string  `json:"product_name"`
	Price       float64 `json:"price"`
	ActualStock int     `json:"actual_stock"`
}

// CreateProductInput represents the JSON payload required to create a Product.
// product_id is omitted because PostgreSQL generates it.
type CreateProductInput struct {
	TenantID    int64   `json:"tenant_id"`
	SKU         string  `json:"sku"`
	ProductName string  `json:"product_name"`
	Price       float64 `json:"price"`
	ActualStock int     `json:"actual_stock"`
}

// Update Product
type UpdateProductInput struct {
	TenantID    int64   `json:"tenant_id"`
	SKU         string  `json:"sku"`
	ProductName string  `json:"product_name"`
	Price       float64 `json:"price"`
	ActualStock int     `json:"actual_stock"`
}

func List(ctx context.Context, db *pgxpool.Pool) ([]ProductListItem, error) {
	rows, err := db.Query(ctx, `
	SELECT
		p.product_id,
		p.tenant_id,
		t.tenant_name,
		p.sku,
		p.product_name,
		p.price,
		p.actual_stock

	FROM products p
	JOIN tenants t
		ON p.tenant_id = t.tenant_id
	ORDER BY p.product_id;
	
`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	products := make([]ProductListItem, 0)

	for rows.Next() {
		var p ProductListItem

		err := rows.Scan(
			&p.ProductID,
			&p.TenantID,
			&p.TenantName,
			&p.SKU,
			&p.ProductName,
			&p.Price,
			&p.ActualStock,
		)
		if err != nil {
			return nil, err
		}
		products = append(products, p)

	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return products, nil
}

func GetByID(
	ctx context.Context,
	db *pgxpool.Pool,
	productID int64,
) (ProductListItem, error) {
	var p ProductListItem

	err := db.QueryRow(ctx, `
		SELECT
			p.product_id,
			p.tenant_id,
			t.tenant_name,
			p.sku,
			p.product_name,
			p.price,
			p.actual_stock
		FROM products p
		JOIN tenants t
			ON p.tenant_id = t.tenant_id
		WHERE p.product_id = $1;
	`, productID).Scan(
		&p.ProductID,
		&p.TenantID,
		&p.TenantName,
		&p.SKU,
		&p.ProductName,
		&p.Price,
		&p.ActualStock,
	)

	if err != nil {
		return ProductListItem{}, err
	}

	return p, nil
}

// Create inserts a Product and returns the identity generated by PostgreSQL.
func Create(
	ctx context.Context,
	db *pgxpool.Pool,
	input CreateProductInput,
) (int64, error) {
	var productID int64

	err := db.QueryRow(ctx, `
		INSERT INTO products (
			tenant_id,
			sku,
			product_name,
			price,
			actual_stock
		)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING product_id;
	`,
		input.TenantID,
		input.SKU,
		input.ProductName,
		input.Price,
		input.ActualStock,
	).Scan(&productID)

	if err != nil {
		return 0, err
	}

	return productID, nil
}

// Update modifies an existing Product.
// RowsAffected is checked because a valid UPDATE statement can succeed
// while matching zero rows when the requested product_id does not exist.
func Update(
	ctx context.Context,
	db *pgxpool.Pool,
	productID int64,
	input UpdateProductInput,
) error {
	commandTag, err := db.Exec(ctx, `
		UPDATE products
		SET
			tenant_id = $1,
			sku = $2,
			product_name = $3,
			price = $4,
			actual_stock = $5
		WHERE product_id = $6;
	`,
		input.TenantID,
		input.SKU,
		input.ProductName,
		input.Price,
		input.ActualStock,
		productID,
	)
	if err != nil {
		return err
	}

	// UPDATE ที่ SQL ถูกต้องแต่หา product_id ไม่เจอจะไม่ถือเป็น SQL error
	// ดังนั้นต้องตรวจจำนวน row ที่ถูกแก้เอง
	if commandTag.RowsAffected() == 0 {
		return pgx.ErrNoRows
	}

	return nil
}

// Delete removes one Product by its primary key.
// A valid DELETE statement does not return an error when no row matches,
// so RowsAffected is used to distinguish "deleted" from "not found".
func Delete(
	ctx context.Context,
	db *pgxpool.Pool,
	productID int64,
) error {
	commandTag, err := db.Exec(ctx, `
		DELETE FROM products
		WHERE product_id = $1;
	`, productID)
	if err != nil {
		return err
	}

	// DELETE สำเร็จในระดับ SQL ได้แม้ไม่มี row ให้ลบ
	// ถ้า affected 0 rows ให้ application ตีความว่า Product ไม่มีอยู่
	if commandTag.RowsAffected() == 0 {
		return pgx.ErrNoRows
	}

	return nil
}
